---
name: Render

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - run: |
          make setup
          make test

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'push' }}

  #   steps:
  #     - uses: actions/checkout@v6

  #     - name: Deploy
  #       run: |
  #         curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
